Bpetzke
NCAR/mlinwrf pull request #2
Opened 2020-09-09 21:33 UTC by petzb

I've added a setup.py for the Python module installation, created a SCons build file for the Fortran piece, and updated the documentation under the root and fortran/ with installation/build instructions.  Please test and DM me if there are any problems/concerns.  Thanks.

2020-09-10 23:03 UTC, djgagne requested changes
I have pointed out a few small changes to address. I was able to get scons to make a so file. As a next step it would be good to write a fortran program to test it from there.

2020-09-10 23:03 UTC, djgagne commented on README.md
> +   $pip install ./setup.py
Should be `pip install .`

2020-09-10 23:03 UTC, djgagne commented on README.md
> +   $conda create --name mlinwrf
It would be good to use conda to install some of the dependencies, such as numpy and scipy, through a command or through an environment.yml files. Tensorflow will need to be installed with pip. Currently tensorflow does not work with numpy>=1.19 so we need to make sure that the last version of numpy below 1.19 is installed.

2020-09-10 23:03 UTC, djgagne commented on fortran/SConstruct
> +env = Environment(F90 = 'ifort',ENV = os.environ, LINK='ld')
Is there a way we can grab the loaded fortran compiler instead of specifying ifort by default? Would using the $FC environment variable work?

2020-09-10 23:03 UTC, djgagne commented on setup.py
> +   install_requires=['numpy', 'pandas', 'tensorflow', 'xarray'],
May need to specify the older numpy version here to minimize conflicts with tensorflow.

2020-09-14 18:28 UTC, petzb commented on README.md
> +   $pip install ./setup.py
Done

2020-09-14 18:30 UTC, petzb commented on README.md
> +   $conda create --name mlinwrf
The README.md is updated with a conda command to downgrade the venv to numpy v. 1.18.5.  If we get more dependencies I'll add en environment.yml but since we only have one besides what's used by pip in the setup.py it's easiest to just have the user run the command described in the README.md.

2020-09-14 18:31 UTC, petzb commented on fortran/SConstruct
> +env = Environment(F90 = 'ifort',ENV = os.environ, LINK='ld')
Done

2020-09-14 18:33 UTC, petzb commented on setup.py
> +   install_requires=['numpy', 'pandas', 'tensorflow', 'xarray'],
I tested this out.  It works fine without the version number.  The user installs the old version of numpy prior to running pip with setup.py so I believe it should just use whatever version is there.

2020-09-16 14:54 UTC, djgagne approved these changes
The changes all look good to me now. Merging.

2020-09-16 14:54 UTC, merged